version: '3'

services:
  app:
    build:
      context: .
    container_name: tasklist
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tasklist?currentSchema=tasklist
      - SPRING_DATASOURCE_USERNAME=xcoder
      - SPRING_DATASOURCE_PASSWORD=secret
    ports:
      - '8080:8080'

  db:
    image: postgres:15.6-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=xcoder
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=tasklist
    volumes:
      - ./src/main/resources/db-init:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
